// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqsEM09yrWKNDqBouH1Ij5T5I0M2pGKFI',
    appId: '1:85410724549:web:d3f9c48c7734da94ec0eac',
    messagingSenderId: '85410724549',
    projectId: 'smartcareassist-96be1',
    authDomain: 'smartcareassist-96be1.firebaseapp.com',
    storageBucket: 'smartcareassist-96be1.appspot.com',
    measurementId: 'G-MYP760JS7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZH5CeeDqAamOF6-AgwOtWgcYxMnafsWo',
    appId: '1:85410724549:android:29b2314746b9f4ceec0eac',
    messagingSenderId: '85410724549',
    projectId: 'smartcareassist-96be1',
    storageBucket: 'smartcareassist-96be1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU3Xn49hp2OYi7kOlXG3wbQoxBi7I62nM',
    appId: '1:85410724549:ios:c4915f4decdda6c7ec0eac',
    messagingSenderId: '85410724549',
    projectId: 'smartcareassist-96be1',
    storageBucket: 'smartcareassist-96be1.appspot.com',
    iosBundleId: 'com.example.zorgtechnologieapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU3Xn49hp2OYi7kOlXG3wbQoxBi7I62nM',
    appId: '1:85410724549:ios:c4915f4decdda6c7ec0eac',
    messagingSenderId: '85410724549',
    projectId: 'smartcareassist-96be1',
    storageBucket: 'smartcareassist-96be1.appspot.com',
    iosBundleId: 'com.example.zorgtechnologieapp',
  );
}
