name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: extractions/setup-just@v1
      - name: Set up flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Run CI job
        run: |
         cd zorgtechnologieapp
         just ci
