name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Change working directory
        run: cd zorg_tech_keuze_app
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12'
      - name: Get dependencies
        run: flutter pub get
      - name: Format code
        run: flutter format --set-exit-if-changed .
      - name: Analyze code
        run: flutter analyze
      - name: Run linter
        run: flutter analyze --no-pub --lints
