name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12'
      - name: Get dependencies
        run: |
         cd zorg_tech_keuze_app
         flutter pub get
      - name: Format code
        run: |
         cd zorg_tech_keuze_app
         dart format --set-exit-if-changed .
      - name: Analyze code
        run: |
         cd zorg_tech_keuze_app
         flutter analyze
      - name: Run linter
        run: |
         cd zorg_tech_keuze_app
         flutter pub get && dart analyze --fatal-infos --fatal-warnings --lint
